language: cpp

#compiler:
#  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libboost-dev 
  - sudo apt-get install g++-4.9

  - deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main

script: pushd build && make
