language: cpp

#compiler:
#  - clang

before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"

  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libboost-dev g++-4.9 llvm-6.0-dev

script:
  - mkdir build
  - cmake ./build
  - pushd build && make
